### PR TITLE
WIP refactor issuance protocol text

### PR DESCRIPTION
**Pull request by wip-abramson**
This is a start to address the issue I raised in #181. 

Not made it all the way through the spec yet - at about Section 7. I seem to be making a fair few changes here, so comments and feedback welcome as I go.

Also, I recommend we update the following diagrams:

- AnonCreds data objects in the introduction. Suggest: remove blinded link secret from holder entirely
- 8. Issuance Flow. Suggest we add a step before 13 that is something like: Remove blinding factor

### CODE REVIEW

**Comment by wip-abramson** [comment]
Getting there...

I am not fully certain how the blinding factor is generated in RSA, so we should check this.

**Comment by wip-abramson** [comment]
Okay, I think the last piece is around `8.4  Receiving a Credential`. 

I need to look into the protocol, but I am pretty certain there should be a step here that transforms the credential signature from the issuer (A,e,v) into (A',e',v') using the blinding factor. Where the credential signature stored by the holder is (A',e',v').

**Comment by wip-abramson** [comment]
So I checked the CL signature code.

This is the line where the prover does the operation to remove the blinding from the credential signature [L635](https://github.com/hyperledger/anoncreds-clsignatures-rs/blob/56fb44364d85b15ca9c33d63bc057e99422a41b6/src/prover.rs#L635). Called from [L237](https://github.com/hyperledger/anoncreds-clsignatures-rs/blob/56fb44364d85b15ca9c33d63bc057e99422a41b6/src/prover.rs#L237) in process_credential_signature.

This line is

`p_cred.v = v_prime.add(&p_cred.v)?;`

Which mutates the V valuse of the credential signature.

**Review by swcurran — APPROVED** [review]

**Comment by wip-abramson** [comment]
Cool! Apologies I counldn't make the call

**Comment by swcurran** [comment]
Thanks for the PR and issues, @wip-abramson.  Working on the spec today — continuing the cleanup.

**Pull request merged**
