### PR TITLE
Small inconsistency fix in CredDef with revocation example 

### PR DESCRIPTION
**Pull request by rodolfomiranda**

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
Thanks

**Comment by swcurran** [comment]
@rodolfomiranda -- could you please fix the DCO (DCO - Developer Certificate of Origin - https://github.com/apps/dco). See the instructions using the link on the "DCO" check above.

**Comment by rodolfomiranda** [comment]
@swcurran , I added the DCO app to my account. I don't know if that will fix or I need to commit something to take effect.

**Comment by swcurran** [comment]
That didn’t fix this PR. You need to force an update to your commit, such that it is signed sufficiently for the DCO. How to do that depends on what GitHub client tools you are using so hard to help further than that.

**Comment by rodolfomiranda** [comment]
> That didn’t fix this PR. You need to force an update to your commit, such that it is signed sufficiently for the DCO. How to do that depends on what GitHub client tools you are using so hard to help further than that.

I think I fix it. DCO error went away

**Pull request merged**
