### PR TITLE
Enable katex support for support latex math

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
Adds support for latex when locally deploying and (hopefully) when rendered in gh-pages.

Some of the existing attempts at latex are rendering properly (see section 8.1 Credential Offer), but some are not (same section). I suspect it is in the text in the spec, not a problem in the engine, but we'll need to look at it. 

@whalelephant -- I'm hoping this works for you and you can take a look.

@ArPhil @TelegramSam @hkny -- can one of you review and approve this PR?

Thanks!

**Comment by swcurran** [comment]
When I change it to just what you suggest and try to run locally, I get an error. Any idea what the problem is?

```
~/repos/anoncreds-spec [enable-katex] 13:26 $ npm run edit
npm ERR! missing script: edit

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/swcur/.npm/_logs/2022-12-07T21_26_20_601Z-debug.log
~/repos/anoncreds-spec [enable-katex !] 13:26 $ cat /home/swcur/.npm/_logs/2022-12-07T21_26_20_601Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'edit' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose stack Error: missing script: edit
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/swcur/repos/anoncreds-spec
6 verbose Linux 4.15.0-200-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "edit"
8 verbose node v10.24.1
9 verbose npm  v6.14.12
10 error missing script: edit
11 verbose exit [ 1, true ]
```

**Comment by andrewwhitehead** [comment]
I think you need to re-fork the main branch and apply only the change I mentioned, then set the `"katex": true` flag in `specs.json`. Right now you don't have an `edit` action because package.json was replaced. Also, when exporting the generated site you will want to copy the `fonts` directory.

**Comment by swcurran** [comment]
And further -- assets, src folders?  Should they be updated as they evolve in the spec-up repo?

**Pull request closed without merging**
