### PR TITLE
update credential definition data model

### PR DESCRIPTION
**Pull request by TimoGlastra**
This PR updates the credential definition data model to reflect the data type that is currently used by the anoncreds implementations in indy credx and indy-sdk and removes some of the indy specific parts of it that already weren't used in the anoncreds model (mainly ref). 

This is the data model that we're proposing (which is basically the model as defined by the AnonCreds implementation in indy-sdk/indy-credx). The main difference is that schemaId is encoded as `schema_id`. I'm not really sure what the standard practice is as there's a lot of different casing for different objects. I can easily change it to be `schemaId`.

```json
{
  "id": "did:indy:sovrin:SGrjRL82Y9ZZbzhUDXokvQ/anoncreds/v0/CLAIM_DEF/54177/latest",
  "schema_id": "did:indy:sovrin:SGrjRL82Y9ZZbzhUDXokvQ/anoncreds/v0/SCHEMA/MemberPass/1.0",
  "type": "CL",
  "tag": "latest",
  "value": {
    "primary": {
      "n": "779...397",
      "r": {
            "birthdate": "294...298",
            "birthlocation": "533...284",
            "citizenship": "894...102",
            "expiry_date": "650...011",
            "facephoto": "870...274",
            "firstname": "656...226",
            "master_secret": "521...922",
            "name": "410...200",
            "uuid": "226...757"
      },
      "rctxt": "774...977",
      "s": "750..893",
      "z": "632...005"
    },
    "revocation": {
      "g": "1 154...813 1 11C...D0D 2 095..8A8",
      "g_dash": "1 1F0...000",
      "h": "1 131...8A8",
      "h0": "1 1AF...8A8",
      "h1": "1 242...8A8",
      "h2": "1 072...8A8",
      "h_cap": "1 196...000",
      "htilde": "1 1D5...8A8",
      "pk": "1 0E7...8A8",
      "u": "1 18E...000",
      "y": "1 068...000"
    }
}
```

This PR also changes all references of CRED_DEF to be Credential Definition as described in #77.

### CODE REVIEW

**Comment by swcurran** [comment]
First pass looks good.  I did notice that you are not converting bullet lists from "*" to "-", as @morrieinmaas is doing.  You might want to verify with him.

Near the end are a bunch of Indy specific things about RevRegEntrys.  Not sure it is here or in the "Revocation" section that we need to formalize the data model that is passed between AnonCreds and the AnonCreds Methods.  Have you thought through that one yet?

Great to hear that `ref` is not used.  That's the one I was worried about. Just getting rid it is great.

**Comment by morrieinmaas** [comment]
> First pass looks good. I did notice that you are not converting bullet lists from "*" to "-", as @morrieinmaas is doing. You might want to verify with him.
> 
I'll have a look at that

> Near the end are a bunch of Indy specific things about RevRegEntrys. Not sure it is here or in the "Revocation" section that we need to formalize the data model that is passed between AnonCreds and the AnonCreds Methods. Have you thought through that one yet?
> 

Unsure atm

**Comment by ArPhil** [comment]
@morrieinmaas, @swcurran , I believe we once had a discussion how to deal with the "Revocation" specific parts / additions. One of the ideas we had, was to describe the "AnonCreds Flows" without Revocation first, because this introduces all the required "Basics". Afterwards (in the "Revocation" section) we wanted to provide the details, which are required for enabling revocation. Reason for this was, that we

a) don`t have to introduce both together (AnonCreds + Revocation)
b) we can reference the "Non Revocation AnonCreds Parts" when describing revocation

For me this approach works, not sure how about you?

**Comment by swcurran** [comment]
@ArPhil -- when we did the "Setup" section, we put in both the non-revocation and revocation sections, and that has not changed here. I think it works.  The reader retains the context of generating a CredDef in the section that follows about how that is extended when adding revocation.  We did put in a separate section the action by the issuer of revoking the credential.

**Review by swcurran — APPROVED** [review]

**Comment by ArPhil** [comment]
@swcurran , you are totally right!

**Review by ArPhil — APPROVED** [review]
Looks good! I was wondering, whether we always should speak about a **Public** Credential Definition and a **Private** Credential Definition explicitely? Sometimes we only write Credential Definition (no **Public** and no **Private**). Although I believe it mostly is clear which part (public, private or both) is meant, it could make things clearer for people not very familiar with the concept.

**Comment by swcurran** [comment]
I think 'Credential Definition" should be the default term and meaning the public/published version, with "Private" added when talking about the internal data.  We might add the "public" modifier if clarification is needed when the both are used together.

**Review by swcurran — APPROVED** [review]
LGTM

**Comment by TimoGlastra** [comment]
This has been updated with changes from main is now ready to merge

**Comment by swcurran** [comment]
A couple of conflicts to resolve and then we are ready to go.  Thanks!

**Review by victormartinez-work — APPROVED** [review]
Looks good to mee too

**Comment by swcurran** [comment]
@TimoGlastra -- can you please address the conflicts in this PR?  We're ready to merge it. Thanks.

**Comment by TimoGlastra** [comment]
Updated! Sorry for the long delay on my side

**Pull request merged**
